djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view
from articles.views import  (article_search_view, article_create_view, article_detail_view)
from accounts.views import login_view, logout_view, register_view

urlpatterns = [
    path('', home_view),
    # path('', dynamic_view),
    path('pantry/recipes/', include('recipes.urls')),
    path('articles/', include('articles.urls')),
    # path('articles/', article_search_view),
    # path('articles/create/', article_create_view, name='article-create'), # Order of operations is important
    # # path('articles/<int:id>/', article_detail_view), Using ID 
    # path('articles/<slug:slug>/', article_detail_view, name="article-detail"), # using slug field
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

djangoproject/recipes/urls.py
from django.urls import path
from .views import (
    recipe_list_view,
    recipe_detail_view,
    recipe_create_view,
    recipe_update_view
)

app_name = 'recipes' # recipes:
urlpatterns = [
    path("", recipe_list_view, name='list'),
    path("create/", recipe_create_view, name='create'),
    path("<int:id>/edit/", recipe_update_view, name='update'),
    path("<int:id>/", recipe_detail_view, name='detail'),
    
]

djangoproject/recipes/models.py
from django.conf import global_settings
from django.db import models
from .validators import validate_unit_of_measurement
from .utils import number_str_to_float
import pint
from django.urls import reverse

# Create your models here.
"""
- Global
    - Ingredients
    - Recipes
- User
    - Igredients
    - Recipes
        - Ingredients
        - Directions for ingredients
"""

class Recipe(models.Model):
    user = models.ForeignKey(global_settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # 
    name = models.CharField(max_length=220) # grillied chicken pasta
    description = models.TextField(blank=True, null=True)
    directions = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse("recipes:detail", kwargs={"id": self.id})
    
    def get_edit_url(self):
        return reverse("recipes:update", kwargs={"id": self.id})
    
    def get_ingredients_childern(self):
        return self.recipeingredient_set.all()

class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=220)
    description = models.TextField(blank=True, null=True)
    quantity = models.CharField(max_length=50)
    quantity_as_float = models.FloatField(blank=True, null=True)
    unit = models.CharField(max_length=50, validators=[validate_unit_of_measurement])
    directions = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return self.recipe.get_absolute_url()

    def convert_to_system(self, system="mks"):
        if self.quantity_as_float is None:
            return None
        ureg = pint.UnitRegistry(system=system)
        measurement = self.quantity_as_float * ureg[self.unit]
        print(measurement)
        return measurement #.to_base_units()

    def as_mks(self):
        # meter, kilogram, second
        measurement = self.convert_to_system(system='mks')
        return measurement.to_base_units()

    def as_imperial(self):
        # miles, pounds, seconds
        measurement = self.convert_to_system(system='imperial')
        return measurement.to_base_units()

    def save(self, *args, **kwargs):
        qty = self.quantity
        qty_as_float, qty_as_float_success = number_str_to_float(qty)
        if qty_as_float_success:
            self.quantity_as_float = qty_as_float
        else:
            self.quantity_as_float = None
        super().save(*args, **kwargs)

djangoproject/recipes/forms.py
from dataclasses import fields
from logging import PlaceHolder
from django import forms
from .models import Recipe, RecipeIngredient

class RecipeForm(forms.ModelForm):
    error_css_class = "error-field"
    required_css_class = "required-field"
    # Help text to name widget
    name = forms.CharField(help_text='This is your help! <a href="/contact">Contact us</a>')

    # Refere documentation for built in widgets
    # name = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control", "placeholder":"Recipe name"}))
    # description = forms.CharField(widget=forms.Textarea(attrs={"rows":3}))
    class Meta:
        model = Recipe
        fields = ['name', 'description', 'directions'] 

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            new_data = {
                "placeholder":f"Recipe {field}",
                "class": "form-control"
            }
            self.fields[str(field)].widget.attrs.update(new_data)

        # self.fields['name'].label = ''
        # self.fields['name'].widget.attrs.update({'class':"form-control-2"})

class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = ['name', 'quantity', 'unit'] 

djangoproject/recipes/views.py
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory
from django.shortcuts import redirect, render, get_object_or_404
from .models import Recipe, RecipeIngredient
from .forms import RecipeForm, RecipeIngredientForm
from django.forms.models import modelform_factory
# Create your views here.
# CRUD - Create Retrieve Update and Delete
# Function Based View (FBV) and Class Based View (CBV)

@login_required
def recipe_list_view(request, id=None):
    qs = Recipe.objects.filter(user=request.user) # User based list 
    context = {
        "object_list": qs
    }
    return render(request, "recipes/list.html", context)

@login_required
def recipe_detail_view(request, id=None):
    obj = get_object_or_404(Recipe, id=id, user=request.user)
    context = {
        "object": obj
    }
    return render(request, "recipes/detail.html", context)

@login_required
def recipe_create_view(request):
    form = RecipeForm(request.POST or None)
    context = {
        "form": form
    }
    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.save()
        return redirect(obj.get_absolute_url())
    return render(request, "recipes/create-update.html", context)

@login_required
def recipe_update_view(request, id=None):
    obj = get_object_or_404(Recipe, id=id, user=request.user)
    form = RecipeForm(request.POST or None, instance=obj)
    # form_2 = RecipeIngredientForm(request.POST or None)
    RecipeIngredientFormFormset = modelformset_factory(RecipeIngredient, form=RecipeIngredientForm, extra=0)
    qs = obj.recipeingredient_set.all()
    formset = RecipeIngredientFormFormset(request.POST or None, queryset=qs)
    # # obj.recipeingredient_set.all()
    # ingredient_forms = []
    # for ingredient_obj in obj.recipeingredient_set.all():
    #     ingredient_forms.append(
    #         RecipeIngredientForm(request.POST or None, instance=ingredient_obj)
    #     )
    context = {
        "form": form,
        "formset": formset,
        # "ingredient_forms": ingredient_forms,
        "object": obj
    }
    # my_forms = all([form.is_valid() for form in ingredient_forms])
    # if my_forms and form.is_valid():
    if all([form.is_valid(), formset.is_valid()]):
        parent = form.save(commit=False)
        parent.save()
        for form in formset:
            child = form.save(commit=False)
            if child.recipe is None:
                print("Added new")
                child.recipe = parent
            child.save()
        # for form_2 in ingredient_forms:
        #     child = form_2.save(commit=False)
        #     child.recipe = parent
        #     child.save()
        context["message"] = 'Data saved'
    return render(request, "recipes/create-update.html", context)

djangoproject/templates/recipes/create-update.html
{% extends "base.html" %}

{% block content %}

<!-- Style set up -->
 <style>
    .ingredient-form {
        border-bottom: 1px solid black;
    }
    .hidden{
        display: none;
    }
 </style>

{% if message %}
<p>{{ message }}</p>
{% endif %}
<div style="margin-top: 30px;">
    <form  action="." method="POST">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        {% for field in form %}
            <div class="{% if field.field.required %}{{ form.required_css_class }}{% endif %}">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                    <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}

        {% if formset %}
        <h3>Ingredients</h3>
        {{ formset.management_form }}
        <div class="ingredient-form-list">
            {% for form in formset %}
                <div class="ingredient-form">
                    {{ form.as_p }} 
                </div>
            {% endfor %}
        </div>
        <!-- {{ formset.as_p }} -->
        <div id="empty-form" class="hidden">{{ formset.empty_form }}</div>
        <button id="add-more" type="button">Add more</button>
        {% endif %}

        <button type="Submit">Save</button>
    </form>
</div>

<script>

    const addMoreBtn = document.getElementById('add-more')
    addMoreBtn.addEventListener('click', add_new_form)
    function add_new_form(event) {
        if (event) {
            event.preventDefault()
        }
        const formCopyTarget = document.getElementById('ingredient-form-list')
        const emptyFormEl = document.getElementById('empty-form').cloneNode(true)
        emptyFormEl.setAttribute('class', 'ingredient-form')
        // console.log(args) // print()
        // Now add new empty form element to our html form
        formCopyTarget.append(emptyFormEl)
    }

</script>

{% endblock content %}

djangoproject/templates/recipes/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ object.name }} {% if object.get_edit_url %} <small><a href="{{ object.get_edit_url }}">Edit</a></small>{% endif %}</h1>
<p>{{ object.descriptions }}</p>
<p>{{ object.directions }}</p>

{% for ingredient in object.get_ingredients_childern %}
<h1>{{ ingredient.name }}</h1>
<p>{{ ingredient.as_imperial }}</p>
<p>{{ ingredient.as_mks }}</p>
{% endfor %}

{% endblock content %}

djangoproject/templates/recipes/list.html
{% extends 'base.html' %}

{% block content %}

<h1>My recipes</h1>
<a href="{% url 'recipes:create' %}">Add recipe</a>
<ul>
    {% for x in object_list %}
        <li><a href='{{ x.get_absolute_url }}'>{{ x.name }}</a></li>
    {% endfor %}

</ul>

{% endblock content%}