djangoproject/articles/urls.py
from django.urls import path
from articles.views import  (article_search_view, article_create_view, article_detail_view)

app_name = 'articles'
urlpatterns = [
    path('', article_search_view, name='search'),
    path('create/', article_create_view, name='create'), # Order of operations is important
    # path('articles/<int:id>/', article_detail_view), Using ID 
    path('<slug:slug>/', article_detail_view, name="detail"), # using slug field
    
]

djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view
from articles.views import  (article_search_view, article_create_view, article_detail_view)
from accounts.views import login_view, logout_view, register_view

urlpatterns = [
    path('', home_view),
    # path('', dynamic_view),
    path('pantry/recipes/', include('recipes.urls')),
    path('articles/', include('articles.urls')),
    # path('articles/', article_search_view),
    # path('articles/create/', article_create_view, name='article-create'), # Order of operations is important
    # # path('articles/<int:id>/', article_detail_view), Using ID 
    # path('articles/<slug:slug>/', article_detail_view, name="article-detail"), # using slug field
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

djangoproject/recipes/urls.py
from django.urls import path
from .views import (
    recipe_list_view,
    recipe_detail_view,
    recipe_create_view,
    recipe_update_view
)

app_name = 'recipes' # recipes:
urlpatterns = [
    path("", recipe_list_view, name='list'),
    path("create/", recipe_create_view, name='create'),
    path("<int:id>/edit/", recipe_update_view, name='update'),
    path("<int:id>/", recipe_detail_view, name='detail'),
    
]

djangoproject/templates/base.html
<!DOCTYPE html>
<html>
    <head>

    </head>
    <body>
        <h1>Hello world!</h1>
        <form action="/articles/" method="GET">
            <input type="text" name="q"/>
            <input type="Submit"/>
        </form>
        {% block content %}
        {% endblock content %}

        {% block name %}
        {% endblock name %}

    </body>
</html>

djangoproject/templates/home-view.html
<!-- Method 2: -->
{% extends "base.html" %}

{% block content %}
<h1>{{ title }} (id: {{ id }})</h1>
<p>{{ content }}</p>

<!-- Rendering list-->
<!-- 
    1. Use for block to get list of items under ul tag
    2. Use if block for conditioned extraction of object
    3. Use li tag for listing
    4. Use a tag to create reference of items
 -->
 <a href="{% url 'articles:create' %}">Create Article</a>
 <ul>
    {% for x in article_list %}
        {% if x.title %}
            <li><a href="{{ x.get_absolute_url }}">{{ x.id }} : {{ x.title }} - {{ x.content }}</a></li>
        {% endif %}
    {% endfor %}
</ul>
{% endblock content %} 

{% block name %}
<h1>Umesh</h1>
{% endblock name %}

<!-- 
Method - 1: 
<h1>{{ title }} (id: {{ id }})</h1>
<p>{{ content }}</p> 

--> 